name: flutter_agent_tools
description: >-
  A Claude Code plugin to help AI coding agents write better Dart and Flutter
  code.
version: 0.1.0

publish_to: none

repository: https://github.com/devoncarew/flutter-agent-tools

environment:
  sdk: ^3.7.0

dependencies:
  dart_mcp: ^0.5.0
  flutter_daemon: ^1.0.1
  unique_names_generator: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  stream_channel: ^2.1.0
  test: ^1.25.0
